Box2D/Testbed/CMakeLists.txt, Box2D/glew/CMakeLists.txt, Box2D/glfw/CMakeLists.txt
=> add missing CMake configuration

Box2D/Box2D/Collision/Shapes/b2PolygonShape.cpp
=> fix minimum vertex distance check

.gitignore, README.md, src/CMakeLists.txt
=> Fix cmake include path. Other minor fixes.

docs/dynamics.md, include/box2d/b2_body.h, include/box2d/b2_joint.h, include/box2d/b2_world.h, src/dynamics/b2_body.cpp, src/dynamics/b2_joint.cpp, src/dynamics/b2_world.cpp, testbed/tests/chain_problem.cpp, testbed/tests/dump_loader.cpp, testbed/tests/polygon_shapes.cpp
Create new contacts when a body is set active.
=> Bug fix from PR #546

src/dynamics/b2_body.cpp, src/dynamics/b2_island.cpp, src/dynamics/b2_motor_joint.cpp, src/dynamics/b2_mouse_joint.cpp, src/dynamics/b2_prismatic_joint.cpp, src/dynamics/b2_world.cpp, testbed/tests/chain.cpp
- The body behaves like a static body
- The body is drawn with a red color
=> Handle zero density better

docs/collision.md, include/box2d/b2_circle_shape.h, include/box2d/b2_joint.h, include/box2d/b2_polygon_shape.h, include/box2d/b2_prismatic_joint.h, include/box2d/b2_wheel_joint.h, include/box2d/b2_world.h, src/dynamics/b2_joint.cpp, src/dynamics/b2_prismatic_joint.cpp, src/dynamics/b2_wheel_joint.cpp, src/dynamics/b2_world.cpp, src/rope/b2_rope.cpp, testbed/CMakeLists.txt, testbed/main.cpp, testbed/tests/car.cpp, testbed/tests/wheel_joint.cpp
Predictive limits help to prevent limit "tunneling" due to discrete simulation.
- prismatic translation limit
- wheel joint translation limit
=> Predictive translation limits

src/dynamics/b2_contact_manager.cpp
=> Removed unnecessary body waking

testbed/main.cpp, testbed/tests/compound_shapes.cpp
This compares different approaches to convex decomposition.
=> Revised compound test

build.sh, include/box2d/b2_edge_shape.h, include/box2d/b2_math.h, unit-test/CMakeLists.txt, unit-test/math_test.cpp
- Changed transform interpolation in b2Sweep to improve performance and accuracy
- Added math unit test
=> Fix for issue #447

include/box2d/b2_body.h, src/dynamics/b2_body.cpp, src/dynamics/b2_world.cpp
=> Static bodies are never awake

src/collision/b2_chain_shape.cpp
Fix #466
Include radius in AABBs computed by chain shape
=> Fix issue #466

testbed/tests/dump_loader.cpp
Reproduce issue #604 
Shows the ball does not gain kinetic energy. The ball is rolling without sliding so it does not lose energy. The surface friction does not provide rolling resistance.
=> Reproduce issue #604

change_list.md, deploy_docs.sh
=> Added change list

include/box2d/b2_distance.h, src/collision/b2_distance.cpp, testbed/tests/shape_cast.cpp
- Check for initial overlap
- Fix initial overlap test for circles
=> Issue 625 shape cast fixes

src/dynamics/b2_revolute_joint.cpp, src/dynamics/b2_rope_joint.cpp, testbed/draw.cpp
=> Issues 623 and 624

include/box2d/b2_dynamic_tree.h, src/collision/b2_dynamic_tree.cpp
=> Remove unused variable

src/dynamics/b2_wheel_joint.cpp, testbed/tests/wheel_joint.cpp
- Fixes #634 
- Wheel joint reaction force was incomplete
- Added reaction force display to wheel joint test
=> Fix for 634

include/box2d/b2_rope.h, src/rope/b2_rope.cpp, testbed/tests/rope.cpp
=> Added triangle-based bending constraint

include/box2d/b2_gear_joint.h, src/dynamics/b2_gear_joint.cpp, testbed/tests/gear_joint.cpp
=> Added assert and comment to ensure dynamic bodies

src/dynamics/b2_distance_joint.cpp, src/dynamics/b2_prismatic_joint.cpp, src/dynamics/b2_revolute_joint.cpp, unit-test/CMakeLists.txt, unit-test/collision_test.cpp, unit-test/hello_world.cpp, unit-test/joint_test.cpp, unit-test/math_test.cpp, unit-test/world_test.cpp
=> Joint fixes and unit test

include/box2d/b2_math.h, unit-test/math_test.cpp
The old interpolation method was better.
Added unit test to ensure this doesn't change.
=> Reverted 447

include/box2d/b2_body.h
SetUserData is no longer needed
=> Remove unnecessary function

.github/workflows/build.yml, README.md, include/box2d/b2_body.h, include/box2d/b2_gear_joint.h, include/box2d/b2_weld_joint.h, src/common/b2_settings.cpp, src/dynamics/b2_body.cpp, src/dynamics/b2_distance_joint.cpp, src/dynamics/b2_gear_joint.cpp, src/dynamics/b2_mouse_joint.cpp, testbed/draw.cpp, testbed/draw.h, testbed/main.cpp, testbed/tests/dump_loader.cpp
Small fixes for:
#681, #686, #689, #690, #691, #692, #694, #695, #696
=> Issue Fixes

docs/dynamics.md, include/box2d/b2_collision.h, include/box2d/b2_world.h, src/dynamics/b2_contact_solver.cpp, src/rope/b2_rope.cpp, testbed/main.cpp, testbed/tests/collision_processing.cpp, testbed/tests/web.cpp, unit-test/doctest.h, unit-test/joint_test.cpp, unit-test/world_test.cpp
=> Miscellaneous fixes

src/dynamics/b2_mouse_joint.cpp
=> Adjust mouse joint damping with time step

testbed/CMakeLists.txt, testbed/tests/benchmark_boxes.cpp
=> Add benchmark test

include/box2d/base.h, include/box2d/box2d.h, include/box2d/collision.h, include/box2d/math_functions.h, include/box2d/types.h, samples/sample_joints.cpp, src/contact.c, src/core.h, src/types.c, src/world.c, src/world.h
=> Friction and restitution mixing rules

include/box2d/box2d.h, samples/CMakeLists.txt, samples/data/background.fs, samples/draw.cpp, samples/draw.h, samples/main.cpp, samples/sample.cpp, samples/sample_continuous.cpp, samples/sample_events.cpp, samples/sample_joints.cpp, src/contact.c, src/contact.h, src/distance.c, src/solver.c, src/table.c, src/types.c, src/world.c, src/world.h
Continuous collision now invokes the pre-solve callback.
Contact events are no longer enabled by default.
=> Fix sensor event order

src/world.c, src/world.h, test/test_world.c
Added unit test to test all world APIs. Fixed access to max speed.
=> World API coverage

README.md, docs/simulation.md, include/box2d/box2d.h, samples/sample_bodies.cpp, samples/sample_collision.cpp, src/body.c, src/shape.c, test/test_world.c
added sensor unit test
added null checks
added WASM link
updated sensor documentation
added b2Body_GetLocalPointVelocity and b2Body_GetWorldPointVelocity
added b2Body_GetMass
#848 #864 #870
=> Sensor unit test

include/box2d/box2d.h, include/box2d/types.h, samples/sample_benchmark.cpp, samples/sample_continuous.cpp, samples/sample_shapes.cpp, src/shape.c, src/shape.h, src/solver.c
adjusted chain time of impact to improve performance
=> chain shape material

.github/workflows/build.yml, CMakeLists.txt, benchmark/CMakeLists.txt, samples/CMakeLists.txt, samples/main.cpp, shared/CMakeLists.txt, src/CMakeLists.txt, src/distance.c, test/CMakeLists.txt
linux samples in CI
fixes for emscripten and mingw
=> Warning as error off by default

CMakeLists.txt, docs/simulation.md, include/box2d/box2d.h, include/box2d/collision.h, include/box2d/math_functions.h, include/box2d/types.h, samples/CMakeLists.txt, samples/data/map01.svg, samples/draw.cpp, samples/main.cpp, samples/sample.h, samples/sample_benchmark.cpp, samples/sample_character.cpp, samples/sample_collision.cpp, samples/sample_world.cpp, shared/human.c, src/CMakeLists.txt, src/aabb.h, src/broad_phase.c, src/broad_phase.h, src/distance.c, src/dynamic_tree.c, src/geometry.c, src/joint.c, src/revolute_joint.c, src/shape.c, test/test_math.c
functions to get and set surface material
function to test AABB overlap
comment and documentation fixes
removed smooth line and restore MSAA from samples
character mover experiments
removed unused variable
tested NLerp accuracy
fixed numerical problem in shape cast
joint limit range increased to 0.99 * B2_PI
added point to character collision planes
sensor benchmark
#918
#920
#919
#917
#916
=> functions to get and set surface material

samples/main.cpp
=> _aligned_free for mingw

samples/CMakeLists.txt, samples/sample_collision.cpp, samples/sample_issues.cpp, src/shape.c
updated CastWorld sample
added sample for issues
fixes #935
=> Cull back-side shape casts against chain shapes
