- Box2D/Testbed/Framework/DebugDraw.cpp
- Box2D/Testbed/Framework/Main.cpp
- Box2D/premake5.lua
Attempting to build the current revision of Box2D on macOS in Xcode currently gives this build error: `Use of undeclared identifier 'nullptr'`
This PR fixes that build error and also standardises some indentation/spacing.
> Fix macOS build

- Contributions/Utilities/ConvexDecomposition/b2Polygon.cpp
Im one of the contributors to Godot engine and we use this utility submodule. It would be nice if this will be fixed here
> Fix memory leak in b2Polygon

- samples/CMakeLists.txt
- samples/MacOSXBundleInfo.plist.in
- samples/main.cpp
PR solve two problems with samples:
* GLSL 1.3 is not available on macOS, bumped to 1.5 (Apple platforms only)
* To avoid problems with locating data files for Samples were build as a bundle where resource files are copied into it
> Fixes for Samples for macOS

- include/box2d/b2_broad_phase.h
- include/box2d/b2_dynamic_tree.h
- include/box2d/b2_settings.h
- include/box2d/b2_world.h
- src/collision/b2_broad_phase.cpp
- src/collision/b2_dynamic_tree.cpp
- src/dynamics/b2_body.cpp
- src/dynamics/b2_fixture.cpp
- src/dynamics/b2_world.cpp
- testbed/CMakeLists.txt
- testbed/draw.cpp
- testbed/main.cpp
- testbed/test.cpp
- testbed/tests/apply_force.cpp
- testbed/tests/platformer.cpp
- testbed/tests/polygon_shapes.cpp
- testbed/tests/rope.cpp
- Enlarged AABBs can shrink if they get too big
- Use AABB centers instead of transform positions to track displacement
- Removed std::sort from pair update by tracking movement in proxies
- Broadphase cost reduced from 0.52ms to 0.35ms in tumbler benchmark
> Optimize broadphase AABB and pair management

- include/box2d/b2_body.h
- include/box2d/b2_joint.h
- include/box2d/b2_settings.h
- src/common/b2_settings.cpp
- src/dynamics/b2_body.cpp
- src/dynamics/b2_distance_joint.cpp
- src/dynamics/b2_fixture.cpp
- src/dynamics/b2_friction_joint.cpp
- src/dynamics/b2_gear_joint.cpp
- src/dynamics/b2_motor_joint.cpp
- src/dynamics/b2_prismatic_joint.cpp
- src/dynamics/b2_pulley_joint.cpp
- src/dynamics/b2_revolute_joint.cpp
- src/dynamics/b2_rope_joint.cpp
- src/dynamics/b2_weld_joint.cpp
- src/dynamics/b2_wheel_joint.cpp
- src/dynamics/b2_world.cpp
- testbed/test.h
> World dump now writes to a file instead of std out

- build_docs.sh
- deploy_docs.sh
- docs/overview.md
- src/collision/b2_polygon_shape.cpp
- unit-test/CMakeLists.txt
- unit-test/collision_test.cpp
- Use first vertex as reference point for polygon centroid and mass calculations
- Added unit test
- Added documentation about world size
- Added scripts to help with documentation
> Fix for issue #422

- include/box2d/b2_distance_joint.h
- include/box2d/b2_joint.h
- include/box2d/b2_revolute_joint.h
- include/box2d/b2_weld_joint.h
- src/dynamics/b2_body.cpp
- src/dynamics/b2_distance_joint.cpp
- src/dynamics/b2_fixture.cpp
- src/dynamics/b2_friction_joint.cpp
- src/dynamics/b2_gear_joint.cpp
- src/dynamics/b2_joint.cpp
- src/dynamics/b2_motor_joint.cpp
- src/dynamics/b2_prismatic_joint.cpp
- src/dynamics/b2_pulley_joint.cpp
- src/dynamics/b2_revolute_joint.cpp
- src/dynamics/b2_rope_joint.cpp
- src/dynamics/b2_weld_joint.cpp
- src/dynamics/b2_world.cpp
- testbed/settings.h
- testbed/tests/cantilever.cpp
- testbed/tests/distance_joint.cpp
- testbed/tests/prismatic_joint.cpp
- testbed/tests/revolute_joint.cpp
- testbed/tests/theo_jansen.cpp
- testbed/tests/wheel_joint.cpp
- Revolute joint limit is now predictive
- Improved debug draw of revolute joints
- All joints with spring-dampers now use stiffness and damping
- Added utility functions to convert frequency and damping ratio to stiffness and damping
- Dump floats according to FLT_DECIMAL_DIG
> Joint polish

- src/dynamics/b2_body.cpp
- unit-test/CMakeLists.txt
- unit-test/world_test.cpp
b2Body::SetTransform now tells b2World to find new contacts at the beginning of the steps.
Added unit test to ensure this works correctly.
> Fix and test for issue 636

- CMakeLists.txt
- include/box2d/b2_body.h
- include/box2d/b2_common.h
- include/box2d/b2_fixture.h
- include/box2d/b2_joint.h
- include/box2d/b2_settings.h
- include/box2d/b2_types.h
- src/CMakeLists.txt
- src/dynamics/b2_fixture.cpp
- testbed/tests/box_stack.cpp
- testbed/tests/ray_cast.cpp
- testbed/tests/sensor.cpp
- Fixes issue #559 
- User can have Box2D include user file b2_user_settings.h by defining B2_USER_SETTINGS
- Allows to override length scale
- Allows custom user data on bodies, fixtures, and joints
- Allows custom allocation and logging
TODO: is there a CMake mechanism I should provide for users to define B2_USER_SETTINGS?
> User settings

- include/box2d/b2_common.h
- include/box2d/b2_contact.h
- include/box2d/b2_fixture.h
- src/dynamics/b2_contact.cpp
- src/dynamics/b2_contact_solver.cpp
- src/dynamics/b2_contact_solver.h
- src/dynamics/b2_fixture.cpp
- testbed/tests/restitution.cpp
Address issue #601
Each fixture has its own restitution velocity threshold.
The minimum threshold of the two touching fixtures is used by the associated contact.
> Added runtime tunable restitution velocity threshold

- unit-test/doctest.h
Referenced issue: #679 
This PR updates Doctest to 2.4.6, the folks over at Doctest provided fixes, including fixing an inline assembly macros that caused issues on M1 Macs.
> Update box2d's version of Doctest to latest version

- include/box2d/b2_collision.h
- include/box2d/b2_polygon_shape.h
- src/collision/b2_collision.cpp
- src/collision/b2_polygon_shape.cpp
- testbed/main.cpp
- testbed/test.cpp
- testbed/tests/convex_hull.cpp
- testbed/tests/skier.cpp
Initially I tried to make gift wrapping handle collinear points better. Conclusion: gift wrapping is a bad algorithm.
So I removed gift wrapping and implemented quickhull. I also added code to explicitly remove collinear points. This turns out to be quite easy once you have a convex hull.
I ran over 200 million randomized tests successfully with test data that is very likely to have collinear points with small numerical deviations. All the tests passed and algorithm correctly rejects very close points and fully collinear points.
I also tested performance at around 150 milliseconds per million hulls.
I split out the convex hull code into a separate function `b2ComputeHull`. This lets people build hulls offline and check for hull validity before using them in `b2PolygonShape`.
This video is …
> Making hull builder more robust

- README.md
- include/box2d/types.h
- samples/sample_continuous.cpp
- src/bitset.c
- src/bitset.h
- src/block_array.c
- src/constraint_graph.c
- src/constraint_graph.h
- src/dynamic_tree.c
- src/shape.c
Joints were incorrectly using the body bit-set for the overflow color.
> Fix null being passed to memcpy

- include/box2d/box2d.h
- include/box2d/collision.h
- samples/sample_bodies.cpp
- samples/sample_collision.cpp
- samples/sample_continuous.cpp
- src/array.h
- src/body.c
- src/broad_phase.c
- src/core.c
- src/distance.c
- src/distance_joint.c
- src/joint.c
- src/manifold.c
- src/revolute_joint.c
- src/shape.c
- src/solver.c
- src/world.c
Wrote a custom capsule versus capsule collider which is more robust than treating capsules as two face polygons.
> New capsule collider

- include/box2d/box2d.h
- include/box2d/collision.h
- include/box2d/types.h
- samples/sample_continuous.cpp
- samples/sample_stacking.cpp
- src/broad_phase.c
- src/core.h
- src/solver.c
- src/world.c
add test for null pair task
add manifold to contact begin events
#803 #806
> Fix missing hit events

- include/box2d/box2d.h
- include/box2d/types.h
- samples/sample_bodies.cpp
- samples/sample_events.cpp
- samples/sample_shapes.cpp
- samples/sample_world.cpp
- src/joint.c
- src/prismatic_joint.c
- src/shape.c
- src/shape.h
- src/types.c
- src/weld_joint.c
- src/world.c
set weld joint reference angle
fixed some angle wrapping bugs
> Explosion features

- .github/workflows/build.yml
- include/box2d/box2d.h
- include/box2d/collision.h
- include/box2d/types.h
- samples/main.cpp
- samples/sample_benchmark.cpp
- samples/sample_collision.cpp
- samples/sample_events.cpp
- src/CMakeLists.txt
- src/body.c
- src/broad_phase.c
- src/contact_solver.c
- src/core.c
- src/core.h
- src/dynamic_tree.c
- src/hull.c
- src/joint.h
- src/manifold.c
- src/motor_joint.c
- src/shape.c
- src/solver.c
- src/timer.c
- src/types.c
- src/weld_joint.c
- src/wheel_joint.c
- src/world.c
- optimized ray and shape cast : 2x faster
- update mass options instead of automatic mass
- fixes for 32-bit Windows build
- b2TreeStats for measuring query performance
- reduced tree node size from 48-bytes to 40-bytes
- fixes for 32-bit Neon
- MSVC warning level 4 and fixes
#814, #815, #813, #809
> Cast benchmark

- include/box2d/box2d.h
- include/box2d/math_functions.h
- src/math_functions.c
- src/world.c
- test/test_determinism.c
- test/test_math.c
> fix atan2 and add more unit tests

- .github/workflows/build.yml
- docs/FAQ.md
- include/box2d/collision.h
- include/box2d/math_functions.h
- include/box2d/types.h
- samples/draw.cpp
- samples/main.cpp
- samples/sample_benchmark.cpp
- samples/sample_events.cpp
- src/contact.c
- src/core.h
- src/geometry.c
- src/math_functions.c
- src/shape.h
- src/solver.c
- src/types.c
- test/test_determinism.c
- test/test_math.c
- adjusted AABB margin based on performance testing
- compute rotation between vectors
- added macOS samples to GitHub actions
#833, #835
> Bounding box performance experiments

- CMakeLists.txt
- docs/overview.md
- docs/simulation.md
- include/box2d/types.h
- samples/sample_events.cpp
- src/contact.c
- src/solver.c
- src/world.c
- src/world.h
Sensor and contact end touch events are now generated whenever a contact is destroyed via user operations, such as:
- destroying a body or shape
- changing filters
- changing body type
- disabling a body
- connecting bodies via joints
Enable hot reloading on MSVC.
> Event bookend

- CMakeLists.txt
Edit and continue only for top level cmake usage
Static link is useful for releasing binary samples, but I'm not doing that yet.
#936
> Removed MSVC static library setting

- include/box2d/box2d.h
- include/box2d/id.h
- include/box2d/types.h
- samples/sample_events.cpp
- src/contact.c
- src/contact.h
- src/physics_world.c
- src/solver.c
`b2ContactBeginTouchEvent` now contains a `b2ContactId` you can hold onto safely and query for the manifold. This lets you get the contact impulses. You can use the end touch event to clear the handle.
> Added b2ContactId for events and access functions

- CMakeLists.txt
- include/box2d/box2d.h
- include/box2d/types.h
- samples/sample_events.cpp
- samples/sample_joints.cpp
- src/array.h
- src/body.c
- src/body.h
- src/joint.c
- src/physics_world.c
- src/sensor.c
- src/sensor.h
- src/shape.c
- src/solver.c
- Removed b2BodyDef::enableSensorHits
- Added access to joint event thresholds
- Removed b2SensorData
- motion locks no longer affect mass
- all visitors now do continuous checks against static sensors
- bullets visitors do continuous checks against all non-bullet sensors
- gave up on supporting fast moving sensors or collecting sensor collision data
- instead people should use ray and shape casts to get detailed swept collision data or use contact events
- added sample that shows how to make an exploding projectile
> Sensor clean up

- include/box2d/types.h
- samples/sample.cpp
- samples/sample_bodies.cpp
- src/body.c
- src/joint.c
- src/solver_set.c
Joint creation may wake a body. This was triggering a validation error while the joint wasn't fully built. I moved the validation closer to the API.
Added motion locking sample. This shows that motion locking is somewhat of a kludge because constraints in the locked direction can be softened.
> Fix joint validation
